#!/usr/bin/env bash
# Debug build of the Safari wrapper project generated by safari-convert.sh
# (SPECS §10, AN §Safari wrapper). Two signing paths:
#   DEVELOPMENT_TEAM=<team id> bash scripts/safari-build.sh
#     -> automatic signing with an Apple Development certificate (Xcode
#        creates it on first use; team id = Xcode ▸ Settings ▸ Apple
#        Accounts). Installs in Safari without any per-launch toggle.
#   bash scripts/safari-build.sh
#     -> ad-hoc (CODE_SIGN_IDENTITY=-); Safari needs "Allow unsigned
#        extensions" on every launch.
# Never pass CODE_SIGNING_ALLOWED=NO/CODE_SIGNING_REQUIRED=NO here — those
# are diagnostic-only overrides (an unsigned binary does not launch on
# Apple Silicon) and must never be treated as a passing build.
set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT=$(find safari -maxdepth 2 -name '*.xcodeproj' -print -quit)
if [ -z "$PROJECT" ]; then
  echo "safari-build.sh: no .xcodeproj found under safari/ — run scripts/safari-convert.sh first" >&2
  exit 1
fi

SCHEME=$(xcodebuild -list -project "$PROJECT" -json | node -e '
  const data = JSON.parse(require("node:fs").readFileSync(0, "utf8"));
  const schemes = data.project.schemes;
  if (!schemes || schemes.length === 0) process.exit(1);
  console.log(schemes[0]);
')

echo "safari-build.sh: project=$PROJECT scheme=$SCHEME"

if [ -n "${DEVELOPMENT_TEAM:-}" ]; then
  echo "safari-build.sh: automatic signing, team=$DEVELOPMENT_TEAM"
  SIGNING=(-allowProvisioningUpdates CODE_SIGN_STYLE=Automatic "DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM")
else
  echo "safari-build.sh: ad-hoc signing (set DEVELOPMENT_TEAM=<id> for a certificate-signed build)"
  SIGNING=(CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=- DEVELOPMENT_TEAM=)
fi

xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -derivedDataPath safari/build \
  "${SIGNING[@]}" \
  build
