#!/usr/bin/env bash
# Ad-hoc Debug build of the Safari wrapper project generated by
# safari-convert.sh (SPECS §10, AN §Safari wrapper, §Resolved unknowns 5).
# This machine has 0 codesigning identities and no Xcode team, so this is
# an ad-hoc build (CODE_SIGN_IDENTITY=-): it needs "Allow unsigned
# extensions" toggled in Safari on every launch. Never pass
# CODE_SIGNING_ALLOWED=NO/CODE_SIGNING_REQUIRED=NO here — those are
# diagnostic-only overrides (an unsigned binary built that way does not
# launch on Apple Silicon) and must never be treated as a passing build.
set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT=$(find safari -maxdepth 2 -name '*.xcodeproj' -print -quit)
if [ -z "$PROJECT" ]; then
  echo "safari-build.sh: no .xcodeproj found under safari/ — run scripts/safari-convert.sh first" >&2
  exit 1
fi

SCHEME=$(xcodebuild -list -project "$PROJECT" -json | node -e '
  const data = JSON.parse(require("node:fs").readFileSync(0, "utf8"));
  const schemes = data.project.schemes;
  if (!schemes || schemes.length === 0) process.exit(1);
  console.log(schemes[0]);
')

echo "safari-build.sh: project=$PROJECT scheme=$SCHEME"

xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration Debug \
  -derivedDataPath safari/build \
  CODE_SIGN_STYLE=Manual \
  CODE_SIGN_IDENTITY=- \
  DEVELOPMENT_TEAM= \
  build
