// Copies the vendored darkreader engine + its license into extension/vendor/.
// extension/vendor/ is git-ignored and regenerated by `npm run pretest`.
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const srcDir = path.join(__dirname, '..', 'node_modules', 'darkreader');
const destDir = path.join(__dirname, '..', 'extension', 'vendor');

fs.mkdirSync(destDir, { recursive: true });

for (const file of ['darkreader.js', 'LICENSE']) {
  fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file));
}

console.log(`vendored darkreader into ${path.relative(process.cwd(), destDir)}`);
